version: 2.1

orbs:
  # The node orb contains a set of prepackaged circleci configuration you can use
  # Orbs commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      # Be sure to change this to major.minor version of python you need to support.
      - image: cimg/python:3.9
    # Checkout the code as the first step.
    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    # Here we're making sure we use just use the global env pip. By default it uses the project root's requirements.txt.
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  If you're requirements.txt isn't in the root directory.
          pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

